language: php

php:
  - 5.3
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

before_script:
  - composer --prefer-source install

script:
  - ./vendor/bin/phpunit -c tests/phpunit.xml.dist

matrix:
  allow_failures:
     - php: hhvm
